# Generated by Django 4.1.1 on 2022-09-16 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 16, 4, 29, 14, 671079)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 16, 4, 29, 14, 670078)),
        ),
    ]
