# Generated by Django 4.1.1 on 2022-09-29 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='staticfiles/image/%Y/%m/%d'),
        ),
    ]
