# Generated by Django 4.1.1 on 2022-09-16 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_alter_comment_date_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 16, 4, 4, 58, 426382)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 16, 4, 4, 58, 425381)),
        ),
    ]
